[package]
name = "hokulea-host"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace
hokulea-proof.workspace = true
hokulea-client.workspace = true
hokulea-eigenda.workspace = true

# Kona
kona-preimage = { workspace = true, features = ["std"] }
kona-host.workspace = true

# Alloy
alloy-rlp.workspace = true
alloy-provider = { workspace = true, features = ["reqwest"] }
alloy-primitives = { workspace = true, features = ["serde"] }

# General
anyhow.workspace = true
tracing.workspace = true
reqwest.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive", "env"] }

[dev-dependencies]
proptest.workspace = true
