set fallback := true

# default recipe to display help information
default:
  @just --list

# Run the client program, either natively or on asterisc, depending on the 'native_or_asterisc' argument.
run-client block_number l1_rpc l1_beacon_rpc l2_rpc rollup_node_rpc eigenda_proxy_rpc native_or_asterisc='native' rollup_config_path='' verbosity='':
  #!/usr/bin/env bash
  set -o errexit -o nounset -o pipefail

  L1_NODE_ADDRESS="{{l1_rpc}}"
  L1_BEACON_ADDRESS="{{l1_beacon_rpc}}"
  L2_NODE_ADDRESS="{{l2_rpc}}"
  OP_NODE_ADDRESS="{{rollup_node_rpc}}"
  EIGENDA_PROXY_ADDRESS="{{eigenda_proxy_rpc}}"
  NATIVE_OR_ASTERISC="{{native_or_asterisc}}"

  L2_CHAIN_ID=$(cast chain-id --rpc-url $L2_NODE_ADDRESS)
  if [ -z "{{rollup_config_path}}" ]; then
    CHAIN_ID_OR_ROLLUP_CONFIG_ARG="--l2-chain-id $L2_CHAIN_ID"
  else
    CHAIN_ID_OR_ROLLUP_CONFIG_ARG="--rollup-config-path $(realpath {{rollup_config_path}})"
  fi

  CLAIMED_L2_BLOCK_NUMBER={{block_number}}
  echo "Fetching configuration for block #$CLAIMED_L2_BLOCK_NUMBER..."

  # Get output root for block
  CLAIMED_L2_OUTPUT_ROOT=$(cast rpc --rpc-url $OP_NODE_ADDRESS "optimism_outputAtBlock" $(cast 2h $CLAIMED_L2_BLOCK_NUMBER) | jq -r .outputRoot)

  # Get the info for the previous block
  AGREED_L2_OUTPUT_ROOT=$(cast rpc --rpc-url $OP_NODE_ADDRESS "optimism_outputAtBlock" $(cast 2h $((CLAIMED_L2_BLOCK_NUMBER - 1))) | jq -r .outputRoot)
  AGREED_L2_HEAD_HASH=$(cast block --rpc-url $L2_NODE_ADDRESS $((CLAIMED_L2_BLOCK_NUMBER - 1)) --json | jq -r .hash)
  L1_ORIGIN_NUM=$(cast rpc --rpc-url $OP_NODE_ADDRESS "optimism_outputAtBlock" $(cast 2h $((CLAIMED_L2_BLOCK_NUMBER - 1))) | jq -r .blockRef.l1origin.number)
  L1_HEAD=$(cast block --rpc-url $L1_NODE_ADDRESS $((L1_ORIGIN_NUM + 30)) --json | jq -r .hash)

  # Move to the workspace root
  cd $(git rev-parse --show-toplevel)

  rm -rf ./data
  mkdir ./data

  echo "Running host program with native client program..."
  cargo r --bin hokulea-example-preloader  -- \
    --l1-head $L1_HEAD \
    --agreed-l2-head-hash $AGREED_L2_HEAD_HASH \
    --claimed-l2-output-root $CLAIMED_L2_OUTPUT_ROOT \
    --agreed-l2-output-root $AGREED_L2_OUTPUT_ROOT \
    --claimed-l2-block-number $CLAIMED_L2_BLOCK_NUMBER \
    --l1-node-address $L1_NODE_ADDRESS \
    --l1-beacon-address $L1_BEACON_ADDRESS \
    --l2-node-address $L2_NODE_ADDRESS \
    --eigenda-proxy-address $EIGENDA_PROXY_ADDRESS \
    --native \
    --data-dir ./data \
    $CHAIN_ID_OR_ROLLUP_CONFIG_ARG \
    {{verbosity}}

