[package]
name = "hokulea-client-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
kona-client.workspace = true
kona-preimage.workspace = true
kona-proof.workspace = true
kona-std-fpvm.workspace = true
kona-std-fpvm-proc.workspace = true

hokulea-proof.workspace = true
hokulea-client.workspace = true

cfg-if.workspace = true

# Execution
op-alloy-consensus.workspace = true
op-revm.workspace = true
alloy-evm.workspace = true

[package.metadata.cargo-machete]
# cfg-if is used by the `client_entry` macro in kona-client
# but somehow machete doesn't see it as a dependency
ignored = ["cfg-if"]