[package]
name = "hokulea-zkvm-verification"
version = "0.1.0"
edition = "2021"

[dependencies]
hokulea-proof.workspace = true
kona-preimage.workspace = true
kona-proof.workspace = true
canoe-verifier.workspace = true
canoe-verifier-address-fetcher.workspace = true