[package]
name = "eigenda"
version = "0.1.0"
edition = "2021"

[dependencies]
kona-derive.workspace = true

# Op Alloy
op-alloy-protocol.workspace = true
alloy-primitives.workspace = true
tracing.workspace = true
async-trait.workspace = true

[features]
default = []
serde = [
  "op-alloy-protocol/serde",
]