[package]
name = "hokulea-proof"
description = "Eigenda Proof SDK"
version = "0.1.0"
edition = "2021"

[dependencies]
kona-preimage.workspace = true
kona-driver.workspace = true
kona-proof.workspace = true
kona-derive.workspace = true

hokulea-eigenda.workspace = true

# Alloy
alloy-primitives.workspace = true

# Op Alloy
op-alloy-protocol.workspace = true
op-alloy-rpc-types-engine.workspace = true
op-alloy-genesis = { workspace = true, features = ["serde"] }
alloy-rlp.workspace = true


tracing.workspace = true

# General
async-trait.workspace = true
