[package]
name = "eigenda-proof"
description = "Eigenda Proof SDK"
version = "0.1.0"
edition = "2021"

[dependencies]
kona-preimage.workspace = true
kona-driver.workspace = true
kona-proof.workspace = true
kona-derive.workspace = true
eigenda.workspace = true

# Alloy

# Op Alloy
op-alloy-genesis = { workspace = true, features = ["serde"] }
alloy-primitives.workspace = true


# General
async-trait.workspace = true

# `std` feature dependencies

# [features]

