name: Kurtosis Devnet

on:
  push:
    branches: [master]
  merge_group:
  pull_request:

env:
  MISE_VERSION: 2024.12.14

jobs:
  kurtosis_devnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: ${{ env.MISE_VERSION }}
          experimental: true
      - run: just run-kurtosis-devnet
      # We build the client here because `just run-client-native-against-devnet`
      # first polls op-geth for a first finalized block, which takes a few minutes,
      # and only after that runs `cargo run` which then builds the client, and takes another
      # few minutes. Better to build here while waiting for first l2 block to finalize.
      - run: just build-native
      - run: just run-client-native-against-devnet
